### ISSUE TITLE
kaspad console log outputs to stdeer instead of stdout

### ISSUE THREAD

**Issue by supertypo** [kaspanet/rusty-kaspa#182]
Rusty kaspad (possibly other executables as well) logs to stderr instead of stdout, on Linux at least.

This adds complexity when processing output using command line tools.

Reproduce:
Can easily be reproduced with: ./kaspad | grep kaspad <- all output will be shown instead of only the lines containing kaspad
However, kaspad -h actually outputs to stdout: ./kaspad --help | grep kaspad <- only one line is output.

Fix: 
Correct logging facility to always do console output to stdout.

**Comment by tiram88** [comment]
The new PR #181 addresses and fixes this issue
