### ISSUE TITLE
\rusty-kaspa\kos\Build.ps1 fails due to invalid wasm-pack command

### ISSUE THREAD

**Issue by equestat** [kaspanet/rusty-kaspa#245]
**Describe the bug**
Was using the Build.ps1 in the \rusty-kaspa\kos\ directory and noticed the following...

# Original with parameters inside the quote - not working:
 & "wasm-pack build --dev --target web --out-name kaspa --out-dir app/wasm"

# Move the quote to only around wasm-pack and parameters after quote - Working:
 & "wasm-pack" build --dev --target web --out-name kaspa --out-dir app/wasm

I think it's because PowerShell treats everything inside the quote as a single command.  Parameters should follow the quotes.  These quotes will need to change on all wasm-pack commands.  The above is just a single example.  

**To Reproduce**
1,)  install prerequisites from "https://github.com/kaspanet/rusty-kaspa#readme"  
2.)  Verify that the running of scripts is allowed on your system and if not, use the Set-ExecutionPolicy command to allow them per your system security requirements.  
3.)  Perform the following from elevated PowerShell Window

git clone https://github.com/kaspanet/rusty-kaspa
cd .\rusty-kaspa\kos\
.\build.ps1

**Expected behavior**
The .\build.ps1 script should begin to build the solution, instead of erroring out due to an invalid command.

**Screenshots**
![image](https://github.com/kaspanet/rusty-kaspa/assets/39092497/80c5c599-65ce-4346-9a8b-8c10c6f4bbc7)
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by aspect** [comment]
Resolved in https://github.com/kaspanet/rusty-kaspa/pull/313
