### ISSUE TITLE
Update Rusty-Kaspa Readme to include adding LLVM/bin to Path environment variable to enable Kos build

### ISSUE THREAD

**Issue by equestat** [kaspanet/rusty-kaspa#246]
**Describe the bug**
When using \rusty-kaspa\kos\Build.ps1, the build errors out as it is not able to find "clang", even though LLVM is installed.  I had to add "C:\Program Files\LLVM\bin" directly to the Path environment variable and reboot or the build process couldn't find clang.  This is not mentioned in the Readme...it says only to "set LIBCLANG_PATH env var pointing to the bin dir of the llvm installation" and I did already have the LIBCLANG_PATH set.  Once I added "C:\Program Files\LLVM\bin" to the "Path" environment variable and rebooted, it was able to find clang and proceed.  

**To Reproduce**
Starting from a clean install of Windows, follow the Kaspa Readme to install prerequisites and clone the rusty-kaspa directory.
Navigate down to the rusty-kaspa/kos directory and open an elevated PowerShell window at this location.  execute \rusty-kaspa\kos\Build.ps1 after applying the fix discussed in issue "https://github.com/kaspanet/rusty-kaspa/issues/245"

the script should fail as it cannot find "clang"

**Expected behavior**
When executing \rusty-kaspa\kos\Build.ps1, it should build successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Kaspad version: [e.g. 0.12.11]

**Additional context**

**Comment by aspect** [comment]
Resolved in https://github.com/kaspanet/rusty-kaspa/pull/313
