### ISSUE TITLE
Add step to rusty-kaspa getting started section to install Git for Windows after the "Install the rust toolchain" step

### ISSUE THREAD

**Issue by equestat** [kaspanet/rusty-kaspa#247]
**Describe the bug**
If a Windows user is starting from a clean system, git for windows will not be present and when a user executes the git command to clone the repo, it will fail 

**To Reproduce**
Start from a clean Windows OS, follow the Getting Started section in the readme file exactly "https://github.com/kaspanet/rusty-kaspa#getting-started" and when you try to run "git clone https://github.com/kaspanet/rusty-kaspa" it will fail.  

**Expected behavior**

When starting from a clean install of Windows OS and following the Getting Started section in the readme file exactly "https://github.com/kaspanet/rusty-kaspa#getting-started", executing "git clone https://github.com/kaspanet/rusty-kaspa" should succeed and clone the repo to the local directory.

Perhaps adding a section after the "Install the rust toolchain" step to install "Git for Windows".  This would be an ideal place to put this step, as the "Install the rust toolchain" step does allow for the automatic installation of Visual Studio.  Git for Windows can be installed using the "Visual Studio Installer".  Once Visual Studio is installed, simply navigate to the Windows start menu, locate the "Visual Studio Installer" and open it.  Once the Visual Studio Installer menu has appeared, select "Modify".  On the next menu, select the tab "Individual Components" and search for "git"
![image](https://github.com/kaspanet/rusty-kaspa/assets/143102144/96f86309-d7b7-4ee4-9357-f6aaf69558ab)

 Check the check box for "Git for Windows" and install.  

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Kaspad version: [e.g. 0.12.11]

**Comment by aspect** [comment]
Resolved in https://github.com/kaspanet/rusty-kaspa/pull/313
