### ISSUE TITLE
\rusty-kaspa\kos\Build.ps1 fails due to missing 'ar.exe'

### ISSUE THREAD

**Issue by equestat** [kaspanet/rusty-kaspa#248]
**Describe the bug**
When executing \rusty-kaspa\kos\Build.ps1 after applying the fixes below....

https://github.com/kaspanet/rusty-kaspa/issues/245
https://github.com/kaspanet/rusty-kaspa/issues/246

the build will fail due to missing 'ar'

**To Reproduce**
When starting from a clean install of Windows OS, follow the Getting Started section in the readme file exactly "https://github.com/kaspanet/rusty-kaspa#getting-started",

Next, apply the 2 fixes discussed in the issues below:
https://github.com/kaspanet/rusty-kaspa/issues/245
https://github.com/kaspanet/rusty-kaspa/issues/246

once that is done, navigate to the directory \rusty-kaspa\kos\, open PowerShell as an admin, making sure that the execution of scripts is enabled on your system per your security needs, and run the Build.ps1 script.

the error below will be thrown.

![image](https://github.com/kaspanet/rusty-kaspa/assets/143102144/b3bf72a8-b79d-4da7-80e9-f088f1d78610)

**Expected behavior**
When executing \rusty-kaspa\kos\Build.ps1 after applying the fixes below....

https://github.com/kaspanet/rusty-kaspa/issues/245
https://github.com/kaspanet/rusty-kaspa/issues/246

the build should succeed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Kaspad version: [e.g. 0.12.11]

**Additional context**
if you navigate down to the "C:\Program Files\LLVM\bin", make a copy of "llvm-ar.exe",  rename the new copy "ar.exe" and then kick off build.ps1 again....seems to build successfully.  This could have other ramifications, though, and not necessarily recommended.

**Comment by aspect** [comment]
Resolved in https://github.com/kaspanet/rusty-kaspa/pull/313
