### ISSUE TITLE
Why is kaspanet.io down?

### ISSUE THREAD

**Issue by unicomp21** [kaspanet/rusty-kaspa#293]
![Screenshot 2023-10-15 at 7 13 01 AM](https://github.com/kaspanet/rusty-kaspa/assets/546301/9aea2a7e-3dcd-4117-9853-d418b24e1699)

**Comment by unicomp21** [comment]
If this is a cloudflare thing, maybe Brave browser and ipfs?

**Comment by someone235** [comment]
This is not related to [rusty-kaspa](https://github.com/kaspanet/rusty-kaspa)

**Comment by aspect** [comment]
A server issue. Will be addressed shortly.

This does not affect https//wallet.kaspanet.io
