### ISSUE TITLE
README instructions for Clang on Linux are causing issue installing 

### ISSUE THREAD

**Issue by cdnsteve** [kaspanet/rusty-kaspa#340]
**Describe the bug**

When following the [README instructions](https://github.com/kaspanet/rusty-kaspa/blob/master/README.md?plain=1#L15) for Clang installation on Linux, it does not suggest running the command as sudo. 

Running the command as described in the README results in an error noted below:
`~/dev/rusty-kaspa$ apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`

Running the same command under sudo resolves this issue.

**To Reproduce**
1. Follow steps under the README for Clang Linux install here: https://github.com/kaspanet/rusty-kaspa/blob/master/README.md?plain=1#L15
2. Run the command on WSL Linux ` apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang`
3. Results in Permission denied, are you root?

**Expected behavior**
The command should install the required libraries.

**Desktop (please complete the following information):**
 - OS: ~/dev/rusty-kaspa$  cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
 - Kaspad version: rusty-kaspa main branch

**Comment by coderofstuff** [comment]
Fixed by #321
