### ISSUE TITLE
The height of the blockchain

### ISSUE THREAD

**Issue by andyoknen** [kaspanet/rusty-kaspa#350]
Hi guys! Please tell me why the height of the blockchain in the explorer jumps up and down? And it just doesn't grow up?

2023/12/10 20:58
![image](https://github.com/kaspanet/rusty-kaspa/assets/24531527/c01f67d9-8be0-4cee-986a-2ae127a4b584)

2023/12/10 20:59
![image](https://github.com/kaspanet/rusty-kaspa/assets/24531527/89d25f24-5d91-4ff5-ba45-42784b1fda2b)

2023/12/11 19:18
![image](https://github.com/kaspanet/rusty-kaspa/assets/24531527/673cd467-477b-4fda-85cb-8d93f1572363)

**Comment by andyoknen** [comment]
Maybe I don't understand something about your blockchain technology, but so far it's more like a scam to fool people

**Comment by aspect** [comment]
Kaspa has no "height" and this is not a _blockchain_, this technology is known as _BlockDAG_, which is quite different.  I will discuss this with the community developers who created and maintain the explorer. I agree that these metrics are a bit misleading to the general public as they represent metrics of the local node which prunes data every ~3 days, retaining only the cryptographic proof of the data continuity as well as the resulting cryptographically-bound transaction dataset.

You are welcome to join Discord and ask the community for explanations on further details, or lookup "Bitcoin pruning" on Google as that is the closest to what you are observing (if framed in the context of traditional blockchains like Bitcoin).

If you seek further explanations, please use Discord. Closing this issue.
