### ISSUE TITLE
'pointer being freed was not allocated' when run cargo run --release --bin kaspad

### ISSUE THREAD

**Issue by taokeqin** [kaspanet/rusty-kaspa#390]
**Describe the bug**
Failed to run release build.
error as bellow:
➜  rusty-kaspa git:(master) ✗ cargo run --release --bin kaspad
    Finished release [optimized] target(s) in 2.24s
     Running `target/release/kaspad`
2024-01-12 21:01:35.040+08:00 [INFO ] kaspad v0.13.3
2024-01-12 21:01:35.040+08:00 [INFO ] Application directory: /Users/xxx/.rusty-kaspa
2024-01-12 21:01:35.040+08:00 [INFO ] Data directory: /Users/xxx/.rusty-kaspa/kaspa-mainnet/datadir
2024-01-12 21:01:35.040+08:00 [INFO ] Logs directory: /Users/xx/.rusty-kaspa/kaspa-mainnet/logs
kaspad(52408,0x7ff84dc10680) malloc: *** error for object 0x50bea081040: pointer being freed was not allocated
kaspad(52408,0x7ff84dc10680) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    52408 abort      cargo run --release --bin kaspad

**To Reproduce**
1. run ` cargo run --release --bin kaspad`

**Expected behavior**
start release version of node successfully.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Darwin mbp.local 22.3.0 Darwin Kernel Version 22.3.0
 - Kaspad version: master at 6655478ecc14e2aae56da8128908e4abf93a1649

**Additional context**
debug version works.

**Comment by coderofstuff** [comment]
@taokeqin can you try it after https://github.com/kaspanet/rusty-kaspa/commit/63523beeb06f7bedd3bef53e9b24aaf414671934 ?

**Comment by taokeqin** [comment]
@coderofstuff Just gave d4ddaf3cd75d002859403f164e3fc9a513940c0b a spin, and it's working perfectly. Appreciate your work!
