### ISSUE TITLE
Support passing a config file to set flags

### ISSUE THREAD

**Issue by coderofstuff** [kaspanet/rusty-kaspa#418]
In golang Kaspad, you are able to pass in config flags by doing

```
kaspad -C config.conf
kaspad --configfile config.conf
```

Provide that same functionality in rusty kaspad.

Relevant file in rust: `kaspad/src/args.rs`

Requirements:
- file format can be whatever is easiest to support
- cli flags passed explicitly should override the values in the config file

**Comment by MuhtasimTanmoy** [comment]
Would like to take this.

**Comment by pablitomilenio** [comment]
Hello @coderofstuff is there anything going on here?
Could you assign this to me?

Thanks and regards from Barcelona

**Comment by aspect** [comment]
Can you please join #development on Kaspa Discord.
