### ISSUE TITLE
error[E0412]: cannot find type `DeterministicHashData` in this scope

### ISSUE THREAD

**Issue by hyperji** [kaspanet/rusty-kaspa#437]
**Describe the bug**
error[E0412]: cannot find type `DeterministicHashData` in this scope

**To Reproduce**
1. Building on Linux
2. then  I run the test, it produces some error with the following code:
cd rusty-kaspa
cargo test --release

the error is in below: 

`error: Seal changed - was: 0xa7a4 now: 0x544d
  --> wallet/core/src/deterministic.rs:59:9
   |
59 | seal! { 0xa7a4, {
   |         ^^^^^^

error[E0412]: cannot find type `DeterministicHashData` in this scope
  --> wallet/core/src/deterministic.rs:78:45
   |
78 | fn make_hashes<T, const N: usize>(hashable: DeterministicHashData<T>) -> [Hash; N]
   |                                             ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
  --> wallet/core/src/deterministic.rs:93:20
   |
93 |     let hashable = DeterministicHashData {
   |                    ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:106:20
    |
106 |     let hashable = DeterministicHashData {
    |                    ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:119:20
    |
119 |     let hashable = DeterministicHashData {
    |                    ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:132:20
    |
132 |     let hashable = DeterministicHashData {
    |                    ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:145:19
    |
145 |     let hashable: DeterministicHashData<[PrvKeyDataId; 0]> = DeterministicHashData {
    |                   ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:145:62
    |
145 |     let hashable: DeterministicHashData<[PrvKeyDataId; 0]> = DeterministicHashData {
    |                                                              ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:158:19
    |
158 |     let hashable: DeterministicHashData<[PrvKeyDataId; 0]> = DeterministicHashData {
    |                   ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `DeterministicHashData` in this scope
   --> wallet/core/src/deterministic.rs:158:62
    |
158 |     let hashable: DeterministicHashData<[PrvKeyDataId; 0]> = DeterministicHashData {
    |                                                              ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0412, E0422.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `kaspa-wallet-core` (lib) due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `kaspa-wallet-core` (lib test) due to 10 previous errors`

**Comment by hyperji** [comment]
![Uploading image.png…]()
this is the error file

**Comment by hyperji** [comment]
![屏幕截图 2024-03-23 174209](https://github.com/kaspanet/rusty-kaspa/assets/10097511/81743274-8a3f-4566-a185-6cbeb0bd3bd4)
this is the file produces the error

**Comment by hyperji** [comment]
is there something wrong with the "0xa7a4" when compiling?
![Uploading image.png…]()

**Comment by hyperji** [comment]
is there something wrong with the "0xa7a4" when compiling?
![屏幕截图 2024-03-23 174909](https://github.com/kaspanet/rusty-kaspa/assets/10097511/f622df94-29fc-4019-9ee2-4a4c89edf71c)

**Comment by hyperji** [comment]
when I chaged 0xa7a4 to 0x544d, it run correctly, without any error.

**Comment by coderofstuff** [comment]
Fixed in #442 and also recognizing the initial fix that was done in #438
