### ISSUE TITLE
Limit the number of blocks returned by GetVirtualChainFromBlock

### ISSUE THREAD

**Issue by coderofstuff** [kaspanet/rusty-kaspa#440]
Currently, GetVirtualChainFromBlock will try to fetch all the blocks that fit the criteria of the RPC call. In 1BPS this is fine, but in 10BPS the data returned can be significantly larger.

To allow for better processing on higher BPS, limit the number of blocks returned by GetVirtualChainFromBlock either by allowing to pass a limit value or by setting a hard limit of blocks per call.

**Comment by coderofstuff** [comment]
This looks to be getting implemented by @D-Stacks in https://github.com/D-Stacks/rusty-kaspa/blob/8397edb4ae138d34c70876382d12c761cc10e1ef/components/consensusmanager/src/session.rs#L253 which is in PR #401

**Comment by D-Stacks** [comment]
> This looks to be getting implemented by @D-Stacks in https://github.com/D-Stacks/rusty-kaspa/blob/8397edb4ae138d34c70876382d12c761cc10e1ef/components/consensusmanager/src/session.rs#L253 which is in PR #401

should i add this directly into this pr? i changed internal consensus api to be able to take a limit, but it isn't implemented on RPC calls directly in #401 , although it would just need a few lines of codes added to implement this.
