### ISSUE TITLE
Panic logs should appear both in the standard log and the error log files

### ISSUE THREAD

**Issue by coderofstuff** [kaspanet/rusty-kaspa#445]
**Describe the bug**
Currently, panic logs only appear in the console and not in log files (both error and standard log file). It should appear in both error logs and the standard logs file.

**To Reproduce**
1. Run the node: `cargo run --bin kaspad`
2. Do anything that causes it to panic
3. The logs only show up on the console 

**Expected behavior**
The panic logs shows up on both log files

**Additional context**
First point of contact: `core/src/panic.rs`

**Comment by gvbgduh** [comment]
taking this one

**Comment by coderofstuff** [comment]
Fixed by #446
