### ISSUE TITLE
Running ./build-web did not generate the 'web' or 'react-native' libraries

### ISSUE THREAD

**Issue by Ligang9** [kaspanet/rusty-kaspa#457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Kaspad version: [e.g. 0.12.11]

**Additional context**

**Comment by Ligang9** [comment]
Nothing happens when running ./build-web

**Comment by aspect** [comment]
Please use the latest branch or development releases - https://github.com/kaspanet/rusty-kaspa/pull/459
