### ISSUE TITLE
Create a panic report with details

### ISSUE THREAD

**Issue by gvbgduh** [kaspanet/rusty-kaspa#465]
**Is your feature request related to a problem? Please describe.**
Follow up on https://github.com/kaspanet/rusty-kaspa/pull/446.
As logs will be available only after the logging system is initiated, it introduces the gap in logs before such the event.
In case of a panic, there will be created a panic report and saved to a file regardless of the logging system status.
Additionally, the panic report may contain details to help with the troubleshooting.

**Describe the solution you'd like**
Write to a file a panic report in case of panic, consider including additional context that can help troubleshooting the issues.

**Describe alternatives you've considered**
Options were considered in https://github.com/kaspanet/rusty-kaspa/pull/446.

**Additional context**
N/A

**Comment by KaffinPX** [comment]
Can be closed now
