### ISSUE TITLE
Weird issue starting integrated node

### ISSUE THREAD

**Issue by Jinxsyns** [kaspanet/rusty-kaspa#478]
**Describe the bug**
Unsure what may have caused it but I all of a sudden can't get the p2p node to start when using the integrated daemon. If i go to a remote node it works though. it just seems to get stuck in starting (it just says not connected and starting)

**To Reproduce**
All I did was open the program. it worked fine the last time I ran it? And like i said switching to a remote node to sync off of works but even switching back to integrated daemon doesn't work to start up the integrated daemon
**Expected behavior**
It to function? I apologize if that sounds rude not my intention it just isn't functioning at all (the node specifically the rest of the program works)

**Screenshots**
![image](https://github.com/kaspanet/rusty-kaspa/assets/130711085/0f2c4a09-0341-4760-94c5-30bb33605087)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Kaspad version: Kaspa NG v0.2.5-eac0efa + Rusty Kaspa v0.14.1

**Additional context**

**Comment by aspect** [comment]
It is more of a Kaspa NG issue, which should be filed at https://github.com/aspectron/kaspa-ng/issues (albeit it does look like the daemon is having trouble starting up, which can be related to Rusty Kaspa daemon itself).

This looks environmental or state/PC related as people are running KNG on Windows without encountering such issues.

Regardless, I have the following questions and suggestions:
1) Does the machine have enough free disk space?
2) Does switching network type have any effect? (mainnet vs testnet-11)
3) What does the Log tab show when this occurs? (Under certain circumstances, the p2p node can start re-indexing the database on startup.  This can take a few minutes on regular machines.  However, when this occurs, logs should state that the node is re-indexing data.  If this is the case, one should wait for the re-indexing to complete.)
4) Can you please exit Kaspa NG and run the node manually from the command line.  You can do this by downloading the latest release from https://github.com/kaspanet/rusty-kaspa/releases and running it as `kaspad --utxoindex`.

Only after you check 3) and try 4) (as running the node manually can present additional clues), can you please go to `C:\Users\<username>\AppData\Local\` and rename `rusty-kaspa` folder to `rusty-kaspa-01` (or you can also delete it). (This will help in case there has been any type of data corruption. This does not occur under normal circumstances but you never know - desktop PCs can exhibit various strange behaviors.)

You should join _Kaspa Discord#help-kaspa-ng_ channel and ask the questions there (there are more people and it is faster to get feedback/ideas in relation to any problems).

LMK if anything I just described helps or has any effect.

**Comment by Jinxsyns** [comment]
It says it is resyncing the utxo index in the logs (put a screenshot for 3) I will let that cook for awhile and see what happens because 1. definitely enough free space 2. testnet 11 works. 3. 
![image](https://github.com/kaspanet/rusty-kaspa/assets/130711085/10550e4c-4919-4be6-9c57-6842c7476812)
 4. I will try if the utxo sync doesn't work after like 24 to 48 hours ( probably around 26ish because I will be needing to use my computer around that time and for what I need to use it for having the wallet run might impact performance)

**Comment by Jinxsyns** [comment]
will update when or if something happens (after I try running it manually from command line first if the utxo sync doesn't happen)

**Comment by Jinxsyns** [comment]
Well it's working now (i waited almost an hour for it last night and nothing happened) so I guess it just needed to resync thank you for your time and the assistance have a wonderful day!

**Comment by aspect** [comment]
@Jinxsyns Can you please give me your machine spec (CPU kind, RAM amount, Storage kind)

**Comment by Jinxsyns** [comment]
it fixed itself I just had to wait for the utxo sync to finish (it just took an unusually long time yesterday) The problem is solved thank you!

**Comment by aspect** [comment]
I am just curious about your setup - the time it takes is proportional to the computer performance. Like I have a powerful dev machine and it usually takes max 5 min.

We need to add a status in the status bar so that instead of "Starting" it says "Re-indexing". to make this less confusing. Something I overlook as I am "used to this".  There is a bit of chicken and the egg problem as the node doesn't connect until it's done re-indexing so this is one condition where the status can't be easily updated...  need to think how to handle this internally..

**Comment by Jinxsyns** [comment]
Oh a 7950x 64gigs and a gen 3 nvme ssd i believe if not gen 4

**Comment by aspect** [comment]
Ok, that's a powerful machine. Thanks for the info. I'll see how the UX can be improved for this.
