### ISSUE TITLE
‘__builtin_thread_pointer’ is not supported on this target

### ISSUE THREAD

**Issue by ellenkampguus** [kaspanet/rusty-kaspa#505]
Command cargo run --release --bin kaspad -- --utxoindex fails. 

  cargo:warning=In file included from c_src/mimalloc/src/alloc.c:14,
  cargo:warning=                 from c_src/mimalloc/src/static.c:23:
  cargo:warning=c_src/mimalloc/include/mimalloc/prim.h: In function ‘_mi_thread_id’:
  cargo:warning=c_src/mimalloc/include/mimalloc/prim.h:240:21: error: ‘__builtin_thread_pointer’ is not supported on this target
  cargo:warning=  240 |   return (uintptr_t)__builtin_thread_pointer();
  cargo:warning=      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=c_src/mimalloc/include/mimalloc/prim.h: In function ‘mi_free’:
  cargo:warning=c_src/mimalloc/include/mimalloc/prim.h:240:21: error: ‘__builtin_thread_pointer’ is not supported on this target
  cargo:warning=  240 |   return (uintptr_t)__builtin_thread_pointer();
  cargo:warning=      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~

  --- stderr

  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_MALLOC_OVERRIDE" "-DMI_DEBUG=0" "-o" "/home/guus/git/rusty-kaspa/target/release/build/libmimalloc-sys-bb86269ea10520b1/out/98cfcaec7182b1d8-static.o" "-c" "c_src/mimalloc/src/static.c" with args cc did not execute successfully (status code exit status: 1).

Linux debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Comment by starkbamse** [comment]
Closing as this was fixed in #519
