### ISSUE TITLE
macOS binaries are not notarized

### ISSUE THREAD

**Issue by martinl** [kaspanet/rusty-kaspa#540]
**Describe the bug**

**To Reproduce**
1. download rusty-kaspa macOS release
2. extract the zip file
3. run ./kaspad --help
4. macOS notifies that the binary is not signed, contact developer
5. here we are

**Expected behavior**
run kaspa macOS binaries

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Kaspad version: rusty-kaspa v0.15.1-rc1
 
**Additional context**
Apple Developer license costs about $100/year, I hope you can manage it

**Comment by KaffinPX** [comment]
You can do right-click => open in Finder to open it, you should run it via terminal anyway.

**Comment by martinl** [comment]
All I can say is that I think that if you publish macOS version of your software it should also be signed by Apple and users should not have to disable OS builtin security protections in order to run it:
https://support.apple.com/en-gb/guide/security/sec5599b66df/web

**Comment by aspect** [comment]
This is not possible via the GitHub release system. These builds are open source and are automatically generated by the integration system on GitHub. To sign something you need to have a central signing authority. To do that using GitHub we would need to publish signing information as open source which defeats the purpose as that would allow anyone to take that and sign anything...

This is not a desktop software that is meant to be released by an individual or a corporate entity. If a party requires a higher level of security, they can follow README instructions and easily build the software from source on their system. If one does that, there won't be any security warnings from the OS.

In essence, this software provides higher level of security than that offered by a typical signed application. When using a signed application, you are relying and trusting the provider that there is nothing malicious in the application. Here, everything is in the open and you don't need to rely or trust anyone. As the old Bitcoin saying goes "Don't trust, verify". ...and even though it means something else, if projected on this, with open source you can "verify", but if an application is signed, you are limited to "trust".

**Comment by martinl** [comment]
https://github.com/marketplace/actions/xcode-notarization

I can help you set it up for github CI if you are interested

**Comment by KaffinPX** [comment]
It's not needed, you can simply run it via right-click and Open on Finder.

**Comment by martinl** [comment]
thanks for the comments, I will set up the macOS CI signing flow in my own fork to get started
