### ISSUE TITLE
Limit option in RPC `getVirtualChainFromBlock`

### ISSUE THREAD

**Issue by ZenVoich** [kaspanet/rusty-kaspa#562]
**Is your feature request related to a problem? Please describe.**
I want to use `getVirtualChainFromBlock` to keep only accepted transactions. But there is no `limit` setting so it always returns all blocks and txs up to the tip. A lot of txs if we start from the pruning point and I suppose a huge amount if I try to call it on historical blocks on archival node.

**Describe the solution you'd like**
Add `limit` option so I can iterate using a suitable batch size.

**Describe alternatives you've considered**
I did not find any other way to check if tx is accepted.

**Comment by D-Stacks** [comment]
how important is the ability for you to supply a limit yourself? will sensible defaults implemented by the node be enough?

**Comment by michaelsutton** [comment]
#454 was merged and pre-released, which should solve this issue.

**Comment by coderofstuff** [comment]
Closed by #454
