### ISSUE TITLE
Problems with batch processing of getVirtualChainFromBlock

### ISSUE THREAD

**Issue by LXHLeaner** [kaspanet/rusty-kaspa#569]
**Describe the bug**
The getVirtualChainFromBlock interface is still slow when synchronising with a block that is 5 hours behind. 
Synchronisation can't keep up with blocks coming out of the chain, so it will never catch up; what should I do?

This is how I'm requesting it, 
is it possible to add additional parameters to specify the length of the returned addedChainBlockHashes?

curl --location '**/info/get-vscp-from-block?startHash=92a46eccd0227701de32d0a58fafb098aabfe0df749958cd70a940ebabd74229&
includeAcceptedTransactionIDs=true' \
--header 'accept: application/json' \
--header 'Content-Type: application/json'

**Comment by KaffinPX** [comment]
this is not related with rusty-kaspa, Kaspa api is an external app(indexer) over rusty-kaspa.

**Comment by coderofstuff** [comment]
Please file it here: https://github.com/kaspa-ng/kaspa-rest-server/issues

@lamer1 fyi
