### ISSUE TITLE
Get transaction by ID similarly to bitcoin core's gettransaction

### ISSUE THREAD

**Issue by Ewemek** [kaspanet/rusty-kaspa#610]
Hello !

**Is your feature request related to a problem? Please describe.**
As a pool operator, I would like to be able to know if, given its ID, a transaction I sent were included in a block, by using rusty-kaspa's gRPC.

**Describe the solution you'd like**
This is a RPC call generally adopted by nodes of other coins. Rusty-kaspa should keep track of all transactions related to any of the loaded wallets (at least when --utxoindex is enabled).

**Describe alternatives you've considered**
* Scanning the blockchain and either storing all tx ids I found, optionally filtering on pubkeys belonging to me.
* Using an external provider such as the explorer.
* Using the spendable UTXOs or GetMempoolEntry calls, but they provide no way to be absolutely certain the transaction was included, or never existed, in particular when multiple transactions are made successively.

**Additional context**
None.

**Comment by KaffinPX** [comment]
https://github.com/kaspanet/rusty-kaspa/pull/401 -- hopefully will be possible in future.

**Comment by Ewemek** [comment]
Okay, thanks for the info !
