### ISSUE TITLE
Evolving Testnet 11 Connect to local node

### ISSUE THREAD

**Issue by rubgithub** [kaspanet/rusty-kaspa#611]
Hi there, I'm new and learing

**Describe the bug**
I'm  Trying to connect to my local node and getting this error:
wRPC -> WebSocket -> WebSocket error: IO error: An existing connection was forcibly closed by the remote host. (os error 10054)
wRPC -> WebSocket -> WebSocket error: WebSocket protocol error: httparse error: invalid HTTP version

**To Reproduce**
1. run kaspa-wallet.exe
2. server 127.0.0.1:16210
3. connect
wRPC -> WebSocket -> WebSocket error: IO error: An existing connection was forcibly closed by the remote host. (os error 10054)
wRPC -> WebSocket -> WebSocket error: WebSocket protocol error: httparse error: invalid HTTP version

**Expected behavior**
Connect to my local node

**Screenshots**
![image](https://github.com/user-attachments/assets/fe3d3258-70b0-4957-8380-d233627a3059)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Kaspad version: [0.15.4]
 - Firewall disabled

**Comment by aspect** [comment]
These questions are best asked in Discord in #development

You are trying to connect to gRPC whereas you need to have wRPC port enabled with --rpclisten-borsh= flag.

Also if network is set correctly (same as node) you don't need to specify port.

You can find more info on RPC at https://kaspa.aspectron.org
