### ISSUE TITLE
Error connecting to DNS seeder

### ISSUE THREAD

**Issue by DilanRona** [kaspanet/rusty-kaspa#612]
**Describe the bug**
Cannot connect to kaspa dns servers.

**To Reproduce**
Start kaspad

**Expected behavior**
Connecting to kaspa dns servers

**Screenshots**

**Desktop (please complete the following information):**
 - OS: fedora 6.11.10-200.fc40.x86_64
 - Kaspad version: kaspad 0.15.0

**Additional context**
installed via cargo command as recommended.
![image](https://github.com/user-attachments/assets/5c4056f0-0159-4e01-adff-0ca1979d8195)

**Comment by DilanRona** [comment]
working now. looks like it was a problem with my ISP itself.

**Comment by ghost** [comment]
Can you explain the issue you had with your ISP because I am having the same issue.

**Comment by DilanRona** [comment]
I'm from South Africa so the ISP problems is guaranteed to not be the same. As for the problems I encountered, it was when I was still on a trial basis for a new fibre installation town wide, and before I got the permanent router.

It was the same with all crypto sites, not just this software.
