### ISSUE TITLE
TypeError: xPrv.derivePath(...).toPrivateKey is not a function

### ISSUE THREAD

**Issue by Demontager** [kaspanet/rusty-kaspa#614]
**Describe the bug**
I tried to use one of example from  wasm/examples/nodejs/javascript/general/derivation.js 
It used to derive kaspa addresses from mnemonic seeds.  I left script untouched except changed path to kaspa node module .
 

**To Reproduce**
When i run script it producing error.
```
$ node derive.js
mnemonic: {
  entropy: '6f62daa640b1f7ca0c9402ed7299d34ef659416231a8881ae102da85b9d3365e',
  phrase: 'hunt bitter praise lift buyer topic crane leopard uniform network inquiry over grain pass match crush marine strike doll relax fortune trumpet sunny silk'
}
seed: c5d1fcaedbc58d17870e37b48581ef2b01c4c63a7fb82d5400b8b32ec68af006caa021f6b58234934e680ad7a49118f1aa25437d0093458dff5b2fd742d4b6d3
publickey 03f0a2d0a87840ded228fcd2d544f86cf765544615a479d0c788ed659ab7f45b6c
address {
  version: 'PubKey',
  prefix: 'kaspa',
  payload: 'qrc2959g0pqda53glnfd238cdnmk24zxzkj8n5x83rkktx4h73dkc5m2z4s4v'
}
address {
  version: 'PubKey',
  prefix: 'kaspa',
  payload: 'qrc2959g0pqda53glnfd238cdnmk24zxzkj8n5x83rkktx4h73dkc5m2z4s4v'
}
change address {
  version: 'PubKey',
  prefix: 'kaspa',
  payload: 'qqrvtndmu2h68q6npvk9d3w89eq7vuulkasxp2t26z7098rpsvf4qvvexy53r'
}
/home/dem/Projects/Kaspa/derive.js:44
    let privateKey = xPrv.derivePath("m/44'/111111'/0'/0/1").toPrivateKey();
                                                             ^

TypeError: xPrv.derivePath(...).toPrivateKey is not a function
    at /home/dem/Projects/Kaspa/derive.js:44:62
    at Object.<anonymous> (/home/dem/Projects/Kaspa/derive.js:76:3)
    at Module._compile (node:internal/modules/cjs/loader:1566:14)
    at Object..js (node:internal/modules/cjs/loader:1718:10)
    at Module.load (node:internal/modules/cjs/loader:1305:32)
    at Function._load (node:internal/modules/cjs/loader:1119:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47

Node.js v23.4.0
```

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Kaspad version: 0.15.2
 - Node.js v23.4.0
 - npm list kaspa
Kaspa@ /home/dem/Projects/Kaspa
└── kaspa@0.13.0

**Additional context**

I have installed @dfns/kaspa-wasm 0.14.1 and manually moved it to node_modules/kaspa/kaspa/kaspa_wasm because kaspa index.js pointing to it index.js
```
globalThis.WebSocket = require('isomorphic-ws');
// globalThis.WebSocket = require('websocket').w3cwebsocket;
module.exports = require('./kaspa/kaspa_wasm');
```

**Comment by aspect** [comment]
You should not need to relocate any files as examples are self contained. node_modules folder is not used in examples. Did you use/download the official wasm release from releases github page and run example in the folder?

You should join Kaspa Discord #development channel, there are a lot of developers using these tools and someone will be able to point out what might be wrong in your process.

**Comment by Demontager** [comment]
@aspect, okay so according to path defined in derivation.js and other example scripts 
` const kaspa = require('../../../../nodejs/kaspa');`
it looking for kaspa module in rusty-kaspa/wasm/nodejs which is empty, therefore i built kaspa_wasm
```
cargo install wasm-pack
cd ~/Projects/Kaspa/rusty-kaspa/wasm
$ wasm-pack build --target nodejs
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.19s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: ✨   Done in 0.44s
[INFO]: 📦   Your wasm pkg is ready to publish at /home/dem/Projects/Kaspa/rusty-kaspa/wasm/pkg
```
And i'm stuck, rusty-kaspa/wasm/nodejs still empty, guess i missed to build something else.

ps. i have joined #develompent channel

**Comment by aspect** [comment]
You should use pre-built wasm to run examples. Try downloading wasm zip from releases and running example from there.

If you want to build from source you need to use corresponding build scripts in the wasm folder (build-node) and also do npm install in the examples (or wasm) root folder (for nodejs websocket dependency).

**Comment by Demontager** [comment]
Alright, precompiled wasm made scripts working including derivation.js
