### ISSUE TITLE
Avoid streams on gRPC because its not supported on web.

### ISSUE THREAD

**Issue by KaffinPX** [kaspanet/rusty-kaspa#94]
![image](https://user-images.githubusercontent.com/73744616/210268150-05fad082-712c-49da-a145-2497dc625367.png)

**Comment by aspect** [comment]
Hi KaffinPx,

We are well aware of this issue.  To address this, at the design stage, we have made sure that the internal kaspa RPC infrastructure is RPC protocol/transport agnostic.  The RPC layer within kaspa is implemented using Rust Traits allowing us to "plug-in" any RPC implementation/library.  For the purpose of backward compatibility, gRPC is the first implementation being done.  JSON-RPC is also available via [Serde](https://serde.rs) although, at the moment I don't think the transport endpoint is implemented.

Anyone will be able to plug in any RPC library if needed.  On my end, for the purposes of PWA (kaspanet web wallet) and KDX. I have been working on a binary WebSocket-based RPC that will interface directly with the WASM layer, then expose WASM functions to JS, effectively allowing anyone using JS to specify a WebSocket endpoint and then use JS functions without worrying about RPC.  Alternatively if using Rust, it will be possible to use Rust functions and if anyone wants to use actual protocols, gRPC and JSON-RPC will be available "out of the box".

**Comment by KaffinPX** [comment]
Anyway if we had a gRPC like Kaspawalletd would be much better

**Comment by aspect** [comment]
Due to backward compatibility requirements with Golang implementation, gRPC won't be changed to remove streams in the near future.  We are using wRPC for web connectivity.  Closing this issue for now.  Ping us on Discord if there are any questions.
